2022-05-10 23:41:00,305 [MainThread] INFO ConfigLoader - Using 'cuda:0' device
2022-05-10 23:41:00,305 [MainThread] INFO TrainingSetup - {'manual_seed': 0, 'model': {'name': 'UNet3D', 'in_channels': 4, 'out_channels': 4, 'layer_order': 'gcr', 'f_maps': 32, 'num_groups': 4, 'final_sigmoid': True, 'is_segmentation': True}, 'trainer': {'checkpoint_dir': '/net/fs01/work01/yasuda/data/multi/', 'resume': None, 'pre_trained': None, 'validate_after_iters': 1000, 'log_after_iters': 100, 'max_num_epochs': 200, 'max_num_iterations': 60000, 'eval_score_higher_is_better': True}, 'optimizer': {'learning_rate': 0.0002, 'weight_decay': 0.0001}, 'loss': {'name': 'DiceLoss', 'weight': None, 'ignore_index': None}, 'eval_metric': {'name': 'MeanIoU', 'ignore_index': None}, 'lr_scheduler': {'name': 'MultiStepLR', 'milestones': [10, 30, 60], 'gamma': 0.2}, 'loaders': {'dataset': 'StandardHDF5Dataset', 'batch_size': 1, 'num_workers': 4, 'raw_internal_path': 'raw', 'label_internal_path': 'label', 'weight_internal_path': None, 'train': {'file_paths': ['/net/fs01/work01/yasuda/data/221x1891x1891/multi/train/'], 'slice_builder': {'name': 'SliceBuilder', 'patch_shape': [32, 64, 64], 'stride_shape': [8, 16, 16]}, 'transformer': {'raw': [{'name': 'Standardize'}, {'name': 'RandomFlip'}, {'name': 'RandomRotate90'}, {'name': 'RandomRotate', 'axes': [[2, 1]], 'angle_spectrum': 15, 'mode': 'reflect'}, {'name': 'ElasticDeformation', 'spline_order': 3}, {'name': 'RandomContrast'}, {'name': 'AdditiveGaussianNoise'}, {'name': 'AdditivePoissonNoise'}, {'name': 'ToTensor', 'expand_dims': True}], 'label': [{'name': 'RandomFlip'}, {'name': 'RandomRotate90'}, {'name': 'RandomRotate', 'axes': [[2, 1]], 'angle_spectrum': 15, 'mode': 'reflect'}, {'name': 'ElasticDeformation', 'spline_order': 0}, {'name': 'ToTensor', 'expand_dims': True}]}}, 'val': {'file_paths': ['/net/fs01/work01/yasuda/data/221x1891x1891/multi/val/'], 'slice_builder': {'name': 'SliceBuilder', 'patch_shape': [32, 64, 64], 'stride_shape': [8, 16, 16]}, 'transformer': {'raw': [{'name': 'Standardize'}, {'name': 'ToTensor', 'expand_dims': True}], 'label': [{'name': 'ToTensor', 'expand_dims': True}]}}}, 'device': device(type='cuda', index=0)}
2022-05-10 23:41:00,305 [MainThread] INFO TrainingSetup - Seed the RNG for all devices with 0
2022-05-10 23:41:01,634 [MainThread] INFO UNet3DTrainer - Using 4 GPUs for training
2022-05-10 23:41:01,634 [MainThread] INFO UNet3DTrainer - Sending the model to 'cuda:0'
2022-05-10 23:41:04,200 [MainThread] INFO UNet3DTrainer - Number of learnable params 4082668
2022-05-10 23:41:04,201 [MainThread] INFO Dataset - Creating training and validation set loaders...
2022-05-10 23:41:05,378 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_0.h5...
2022-05-10 23:41:05,397 [MainThread] INFO HDF5Dataset - Input stats: min=109, max=150, mean=128.79134440925506, std=3.9980538594412955
2022-05-10 23:41:05,404 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_0.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,426 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_1.h5...
2022-05-10 23:41:05,443 [MainThread] INFO HDF5Dataset - Input stats: min=109, max=180, mean=129.31783752486342, std=4.7047384107932615
2022-05-10 23:41:05,451 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_1.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,453 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_2.h5...
2022-05-10 23:41:05,470 [MainThread] INFO HDF5Dataset - Input stats: min=110, max=156, mean=130.02076423360762, std=4.650120044111711
2022-05-10 23:41:05,475 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_2.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,476 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_3.h5...
2022-05-10 23:41:05,492 [MainThread] INFO HDF5Dataset - Input stats: min=108, max=151, mean=129.24791296990932, std=4.386355229548626
2022-05-10 23:41:05,497 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_3.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,498 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_4.h5...
2022-05-10 23:41:05,512 [MainThread] INFO HDF5Dataset - Input stats: min=83, max=218, mean=130.73164474193203, std=6.632527452732926
2022-05-10 23:41:05,517 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_4.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,518 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_5.h5...
2022-05-10 23:41:05,534 [MainThread] INFO HDF5Dataset - Input stats: min=83, max=196, mean=130.63924390237815, std=4.56628925059542
2022-05-10 23:41:05,541 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_5.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,542 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_6.h5...
2022-05-10 23:41:05,559 [MainThread] INFO HDF5Dataset - Input stats: min=105, max=165, mean=130.01115328846063, std=4.946653856426405
2022-05-10 23:41:05,566 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_6.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,567 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_7.h5...
2022-05-10 23:41:05,584 [MainThread] INFO HDF5Dataset - Input stats: min=107, max=197, mean=130.03489239784471, std=5.659657082254368
2022-05-10 23:41:05,592 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_7.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,593 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_8.h5...
2022-05-10 23:41:05,610 [MainThread] INFO HDF5Dataset - Input stats: min=110, max=151, mean=129.15257219439516, std=4.243037335568198
2022-05-10 23:41:05,616 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/train/multi_8.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,620 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_0.h5...
2022-05-10 23:41:05,635 [MainThread] INFO HDF5Dataset - Input stats: min=109, max=150, mean=128.79134440925506, std=3.9980538594412955
2022-05-10 23:41:05,637 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_0.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,640 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_1.h5...
2022-05-10 23:41:05,657 [MainThread] INFO HDF5Dataset - Input stats: min=109, max=180, mean=129.31783752486342, std=4.7047384107932615
2022-05-10 23:41:05,659 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_1.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,661 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_2.h5...
2022-05-10 23:41:05,677 [MainThread] INFO HDF5Dataset - Input stats: min=110, max=156, mean=130.02076423360762, std=4.650120044111711
2022-05-10 23:41:05,679 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_2.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,682 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_3.h5...
2022-05-10 23:41:05,698 [MainThread] INFO HDF5Dataset - Input stats: min=108, max=151, mean=129.24791296990932, std=4.386355229548626
2022-05-10 23:41:05,701 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_3.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,703 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_4.h5...
2022-05-10 23:41:05,719 [MainThread] INFO HDF5Dataset - Input stats: min=83, max=218, mean=130.73164474193203, std=6.632527452732926
2022-05-10 23:41:05,721 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_4.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,723 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_5.h5...
2022-05-10 23:41:05,740 [MainThread] INFO HDF5Dataset - Input stats: min=83, max=196, mean=130.63924390237815, std=4.56628925059542
2022-05-10 23:41:05,742 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_5.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,744 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_6.h5...
2022-05-10 23:41:05,761 [MainThread] INFO HDF5Dataset - Input stats: min=105, max=165, mean=130.01115328846063, std=4.946653856426405
2022-05-10 23:41:05,763 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_6.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,765 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_7.h5...
2022-05-10 23:41:05,782 [MainThread] INFO HDF5Dataset - Input stats: min=107, max=197, mean=130.03489239784471, std=5.659657082254368
2022-05-10 23:41:05,788 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_7.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,789 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_8.h5...
2022-05-10 23:41:05,805 [MainThread] INFO HDF5Dataset - Input stats: min=110, max=151, mean=129.15257219439516, std=4.243037335568198
2022-05-10 23:41:05,807 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/221x1891x1891/multi/val/multi_8.h5
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 88, in __init__
    self.labels = self.fetch_and_check(input_file, label_internal_path)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 148, in fetch_and_check
    datasets = self.fetch_datasets(input_file_h5, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in fetch_datasets
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 287, in <listcomp>
    return [input_file_h5[internal_path][...] for internal_path in internal_paths]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/group.py", line 307, in __getitem__
    raise TypeError("Accessing a group is done with bytes or str, "
TypeError: Accessing a group is done with bytes or str,  not <class 'ellipsis'>
2022-05-10 23:41:05,809 [MainThread] INFO Dataset - Number of workers for train/val dataloader: 4
2022-05-10 23:41:05,810 [MainThread] INFO Dataset - 4 GPUs available. Using batch_size = 4 * 1
2022-05-10 23:41:05,810 [MainThread] INFO Dataset - Batch size for train/val loader: 4
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/bin/train3dunet", line 10, in <module>
    sys.exit(main())
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/train.py", line 27, in main
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/unet3d/trainer.py", line 92, in build
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/utils.py", line 302, in get_train_loaders
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 290, in __init__
    assert len(self.datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore[arg-type]
AssertionError: datasets should not be an empty iterable
