2022-05-12 16:53:51,240 [MainThread] INFO ConfigLoader - Using 'cuda:0' device
2022-05-12 16:53:51,240 [MainThread] INFO TrainingSetup - {'manual_seed': 0, 'model': {'name': 'UNet3D', 'in_channels': 1, 'out_channels': 1, 'layer_order': 'gcr', 'f_maps': 32, 'num_groups': 8, 'final_sigmoid': True, 'is_segmentation': True}, 'trainer': {'checkpoint_dir': '/net/fs01/work01/yasuda/data/myosin/UNet3D/GenericAveragePrecision', 'resume': None, 'pre_trained': None, 'validate_after_iters': 20, 'log_after_iters': 20, 'max_num_epochs': 50, 'max_num_iterations': 100000, 'eval_score_higher_is_better': True}, 'optimizer': {'learning_rate': 0.0002, 'weight_decay': 0.0001}, 'loss': {'name': 'DiceLoss', 'weight': None, 'ignore_index': None}, 'eval_metric': {'name': 'GenericAveragePrecision', 'metric': 'ap'}, 'lr_scheduler': {'name': 'MultiStepLR', 'milestones': [10, 30, 60], 'gamma': 0.2}, 'loaders': {'dataset': 'StandardHDF5Dataset', 'batch_size': 1, 'num_workers': 4, 'raw_internal_path': 'raw', 'label_internal_path': 'label', 'weight_internal_path': None, 'train': {'file_paths': ['/net/fs01/work01/yasuda/data/myosin/train/'], 'slice_builder': {'name': 'SliceBuilder', 'patch_shape': [32, 64, 64], 'stride_shape': [8, 16, 16]}, 'transformer': {'raw': [{'name': 'Standardize'}, {'name': 'RandomFlip'}, {'name': 'RandomRotate90'}, {'name': 'RandomRotate', 'axes': [[2, 1]], 'angle_spectrum': 15, 'mode': 'reflect'}, {'name': 'ElasticDeformation', 'spline_order': 3}, {'name': 'RandomContrast'}, {'name': 'AdditiveGaussianNoise'}, {'name': 'AdditivePoissonNoise'}, {'name': 'ToTensor', 'expand_dims': True}], 'label': [{'name': 'RandomFlip'}, {'name': 'RandomRotate90'}, {'name': 'RandomRotate', 'axes': [[2, 1]], 'angle_spectrum': 15, 'mode': 'reflect'}, {'name': 'ElasticDeformation', 'spline_order': 0}, {'name': 'ToTensor', 'expand_dims': True}]}}, 'val': {'file_paths': ['/net/fs01/work01/yasuda/data/myosin/val/'], 'slice_builder': {'name': 'SliceBuilder', 'patch_shape': [32, 64, 64], 'stride_shape': [32, 64, 64]}, 'transformer': {'raw': [{'name': 'Standardize'}, {'name': 'ToTensor', 'expand_dims': True}], 'label': [{'name': 'ToTensor', 'expand_dims': True}]}}}, 'device': device(type='cuda', index=0)}
2022-05-12 16:53:51,241 [MainThread] INFO TrainingSetup - Seed the RNG for all devices with 0
2022-05-12 16:53:52,496 [MainThread] INFO UNet3DTrainer - Using 4 GPUs for training
2022-05-12 16:53:52,496 [MainThread] INFO UNet3DTrainer - Sending the model to 'cuda:0'
2022-05-12 16:53:55,046 [MainThread] INFO UNet3DTrainer - Number of learnable params 4081267
2022-05-12 16:53:55,046 [MainThread] INFO Dataset - Creating training and validation set loaders...
2022-05-12 16:53:56,063 [MainThread] INFO HDF5Dataset - Loading train set from: /net/fs01/work01/yasuda/data/myosin/train/...
2022-05-12 16:53:56,064 [MainThread] ERROR HDF5Dataset - Skipping train set: /net/fs01/work01/yasuda/data/myosin/train/
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 75, in __init__
    input_file = self.create_h5_file(file_path, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 283, in create_h5_file
    return h5py.File(file_path, 'r')
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/files.py", line 455, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/net/fs01/work01/yasuda/data/myosin/train/', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2022-05-12 16:53:56,067 [MainThread] INFO HDF5Dataset - Loading val set from: /net/fs01/work01/yasuda/data/myosin/val/...
2022-05-12 16:53:56,067 [MainThread] ERROR HDF5Dataset - Skipping val set: /net/fs01/work01/yasuda/data/myosin/val/
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 232, in create_datasets
    dataset = cls(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 270, in __init__
    super().__init__(file_path=file_path,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 75, in __init__
    input_file = self.create_h5_file(file_path, internal_paths)
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/hdf5.py", line 283, in create_h5_file
    return h5py.File(file_path, 'r')
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/files.py", line 455, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/net/fs01/work01/yasuda/data/myosin/val/', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2022-05-12 16:53:56,068 [MainThread] INFO Dataset - Number of workers for train/val dataloader: 4
2022-05-12 16:53:56,068 [MainThread] INFO Dataset - 4 GPUs available. Using batch_size = 4 * 1
2022-05-12 16:53:56,068 [MainThread] INFO Dataset - Batch size for train/val loader: 4
Traceback (most recent call last):
  File "/home/people/yasuda/.conda/envs/3dunet/bin/train3dunet", line 10, in <module>
    sys.exit(main())
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/train.py", line 27, in main
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/unet3d/trainer.py", line 92, in build
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/pytorch3dunet-1.3.3-py3.9.egg/pytorch3dunet/datasets/utils.py", line 302, in get_train_loaders
  File "/home/people/yasuda/.conda/envs/3dunet/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 290, in __init__
    assert len(self.datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore[arg-type]
AssertionError: datasets should not be an empty iterable
